name: Build and deploy
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "adrien.dubois35@gmail.com"
        git config --global user.name "Armitage35"
        git remote set-url origin https://f9c4efca02407769111aad1e4755aa5ad511f372@github.com/Armitage35/cci_doc_v2.git
        npm run deploy
