name: Build and deploy
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.USERNAME }}
        git remote set-url origin ${{ secrets.DEPLOY_TOKEN }}@github.com/your_github_username>/your_repo>.git
        npm run deploy
