name: markdown-link-check

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown links check
        uses: ruzickap/action-my-markdown-link-checker@v1
